/** @type {import('prettier').Config} */
module.exports = {
  // semi: false,
  // singleQuote: true,
  // printWidth: 100,
  // tabWidth: 2,
  // trailingComma: 'all',
  // arrowParens: 'avoid',
  // bracketSpacing: true,
  // jsxBracketSameLine: false,
  // endOfLine: 'auto',
  // quoteProps: 'consistent',
  // useTabs: false,
  // proseWrap: 'preserve',
  // htmlWhitespaceSensitivity: 'strict',
  // embeddedLanguageFormatting: 'auto',
  // vueIndentScriptAndStyle: true,
  // jsxSingleQuote: false,
  // jsxPrintWidth: 120,
  // tailwindcssWrapAttributes: true,
  overrides: [
    {
      files: ['*.json', '*.json5', '*.jsonc'],
      options: {
        // printWidth: 120,
        // tabWidth: 2,
      },
    },
  ],
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^@/types/(.*)$',
    '^@/config/(.*)$',
    '^@/lib/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/components/(.*)$',
    '^@/registry/(.*)$',
    '^@/app/(.*)$',
    '',
    '^(?!.*[.]css$)[./].*$',
    '.css$',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
