import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { DialogInput } from "@/components/dialog-search";
import { Button } from "@/components/ui/button";
import { MagnifyingGlassIcon } from "@radix-ui/react-icons";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const navigate = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[2000px] pt-14">
        <section className="h-full w-full overflow-hidden">
          <div className="flex flex-col items-center justify-end bg-background py-24 md:py-12">
            <div className="flex flex-col items-center justify-center ">
              <h1 className="pb-4 text-9xl">Discover Twitch Vods</h1>
              <p className="pb-10 text-2xl">
                Watch twitch past broadcasts streams Start by Typing twitch
                username...
              </p>
            </div>
            <DialogInput>
              <Button className="text-text bg-button-foreground px-40 text-white">
                <MagnifyingGlassIcon />
                Search Steamer
              </Button>
            </DialogInput>
          </div>
        </section>
        <section></section>
      </main>
    </>
  );
}
