import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { DialogInput } from "@/components/dialog-search";
import { Button } from "@/components/ui/button";
import { MagnifyingGlassIcon } from "@radix-ui/react-icons";
import { GetServerSidePropsContext } from "next";
import { getAccessToken, getGameClips, getTopGames } from "@/shared/api/axios";
import EmblaCarousel from "@/components/carousel/EmblaCarousel";

const inter = Inter({ subsets: ["latin"] });
export async function getServerSideProps(context: GetServerSidePropsContext) {
  const id = context?.params?.id as string;
  const accessToken = await getAccessToken();

  const games = await getTopGames(accessToken);
  const clip = getGameClips(accessToken);

  return { props: { games } };
}

export default function Home({ games, clip }: any) {
  const navigate = useRouter();

  console.log("CLIP", clip);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[2000px] overflow-x-hidden">
        <section className="w-full overflow-x-hidden">
          <div className="flex flex-col items-center justify-end bg-background pb-10 pt-24 md:py-12">
            <div className="flex flex-col items-center justify-center ">
              <h1 className="pb-4 text-9xl">Discover Twitch Vods</h1>
              <p className="pb-10 text-2xl">
                Watch twitch past broadcasts streams Start by Typing twitch
                username...
              </p>
            </div>
            <DialogInput>
              <Button className="bg-button-foreground px-40 text-text text-white">
                <MagnifyingGlassIcon />
                Search Steamer
              </Button>
            </DialogInput>
          </div>
        </section>
        <section className="relative  flex w-full flex-col items-center justify-center rounded-2xl ">
          <div>
            <h1 className="text-7xl pb-3 text-white">Top streams Now</h1>
          </div>
          <EmblaCarousel slides={games}></EmblaCarousel>
        </section>
        <section></section>
      </main>
    </>
  );
}
